
  CREATE OR REPLACE FORCE EDITIONABLE VIEW "PR_DEPARTMENT_STYLE_V" ("LOCALID", "HOSTREF", "DEPARTMENTSTYLE", "WEBSITE", "DEPARTMENT", "STYLE", "SORTORDER") AS 
  SELECT LOCALID,
		HOSTREF,
		DEPARTMENTSTYLE,
		WEBSITE,
		DEPARTMENT,
		STYLE,
		SORTORDER
FROM
	PR_DEPARTMENT_STYLE_V_BASE WHERE DEPARTMENT IS NOT NULL;
