
  CREATE OR REPLACE FORCE EDITIONABLE VIEW "PR_DEPARTMENT_V" ("CATALOG", "DEPARTMENT", "DESCRIPTION", "HOSTREF", "LOCALEID", "NAME", "PARENTDEPARTMENT", "SALESORG", "SORTORDER", "WEBSITE") AS 
  SELECT 
			ptc_str_2typeInfoLCSLifecycl CATALOG,
			ptc_str_3typeInfoLCSLifecycl DEPARTMENT,
			ptc_str_4typeInfoLCSLifecycl DESCRIPTION,
			ptc_str_5typeInfoLCSLifecycl HOSTREF,
			ptc_str_6typeInfoLCSLifecycl LOCALEID,
			ptc_str_7typeInfoLCSLifecycl NAME,
			ptc_str_8typeInfoLCSLifecycl PARENTDEPARTMENT,
			ptc_str_9typeInfoLCSLifecycl SALESORG,
			ptc_str_10typeInfoLCSLifecyc SORTORDER,
			ptc_str_11typeInfoLCSLifecyc WEBSITE
FROM LCSLIFECYCLEMANAGED 
WHERE FLEXTYPEIDPATH = '\49998960\50080510'
--WHERE FLEXTYPEREFIDXXX = '10183113'
;

